name: 📦 Make QGIS Plugin Zip for Manual Installs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  build_package:
    name: Build Package 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/upload-artifact@v7
        with:
          name: animation_workbench
          path: animation_workbench
