name: Create a release
on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:release-3_34
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix Python command
        run: apt-get update && apt-get install -y python-is-python3

      - name: Install python
        uses: actions/setup-python@v5

      - name: Install plugin dependencies
        run: pip install -r requirements-dev.txt

      - name: Get experimental info
        id: get-experimental
        run: |
           echo "IS_EXPERIMENTAL=$(python -c "import json; f = open('config.json'); data=json.load(f); print(str(data['general']['experimental']).lower())")" >> "$GITHUB_OUTPUT"

      - name: Generate zip
        run: python admin.py generate-zip

      - name: get zip details
        id: get-zip-details
        run: |
          echo "ZIP_PATH=dist/$(ls dist)" >> "$GITHUB_OUTPUT"
          echo "ZIP_NAME=$(ls dist)" >> "$GITHUB_OUTPUT"

      - name: Create release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          prerelease: ${{ steps.get-experimental.outputs.IS_EXPERIMENTAL }}
          draft: false
          files: ${{ steps.get-zip-details.outputs.ZIP_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: release
      - name: Update custom plugin repository to include latest release
        run: |
          python admin.py --verbose generate-plugin-repo-xml
          echo " " >> docs/repository/plugins.xml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /__w/QGISAnimationWorkbench/QGISAnimationWorkbench

          git add -A
          git commit -m "Update on plugins.xml"
          git push origin release
